
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate app bundle
        run: ./gradlew app:bundleRelease --stacktrace

      - name: Sign app bundle
        run: |
          jarsigner -keystore app/*.jks \
          -storepass ${{ secrets.SIGNING_KEY_STORE_PASSWORD }} -keypass ${{ secrets.SIGNING_KEY_PASSWORD }} \
          app/build/release/app-release.aab ${{ secrets.SIGNING_KEY_ALIAS }}

#      - name: Build APK
#        run: bash ./gradlew assembleDebug --stacktrace
#      - name: Upload APK
#        uses: actions/upload-artifact@v3
#        with:
#          name: app-debug.apk
#          path: app/build/outputs/apk/debug/app-debug.apk

#      - name: Build Release APK
#        env:
#          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
#          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
#          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
#          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
#        run: bash ./gradlew assembleRelease
#
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "app/build/release/*"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}